.TH AUTOBLOG 1
.SH NAME
autoblog \- automatic blog and RSS system
.SH SYNOPSIS
.B autoblog
.RB [ \-n \ new\ post ]
.RB [ \-p \ publish\ draft ]
.RB [ \-e \ edit\ draft ]
.RB [ \-v \ view\ draft ]
.RB [ \-t \ delete\ draft ]
.RB [ \-r \ revise\ published ]
.RB [ \-c \ change\ title]
.RB [ \-o \ view\ published ]
.RB [ \-d \ delete\ published ]
.RB [ \-l \ list\ all\ published ]
.SH DESCRIPTION
.B autoblog
generates a blog post page and RSS feed.
.SH OPTIONS
The options are as follows:
.TP
.BR \-n
Prompt the user to write a new blog post in HTML
.TP
.BR \-p
Publish one of the posts stored in the .drafts directory. 
.TP
.BR \-e
Edit one of the posts stored in the .drafts directory.
.TP
.BR \-v
View one of the posts stored in the .drafts directory.
.TP
.BR \-t
Delete one of the posts stored in the .drafts directory.
.TP
.BR \-r
Revise a published post stored in the blog directory.
.TP
.BR \-c
Change a published post's title.
.TP
.BR \-o
View a published post stored in the blog directory on your default browser.
.TP
.BR \-d
Delete a published post stored in the blog directory.
.TP
.BR \-l
List all posts stored in the blog directory.
.P
Only one option at a time can be used.
.P
Run the script inside your website's main directory and edit the website and author
to match your own information. Make sure that the rest of the variables are properly
set to match your website's structure. By default, all blog posts are stored in
.I blog/
.P
.B autoblog
will search for <!--BLOG--> inside
.I index.html
and
.I rss.xml
in order to put the blog post listings and RSS feed respectively. Inside
.I blogindex.html
however, it will search for <!--BLOG [Month Year]--> (e.g <!--BLOG January 1800->).
.P
A
.I template.html
file needs to exist in your main directory in order for the
script to run properly. That file is how you want your blog post's generated page
to look like. The
.I TITLE
,
.I HEADER
and
.I AUTHOR
fields must exist and be left as is.
.SH AUTHORS
Christos Margiolis <christos@christosmarg.xyz>
