#!/bin/sh

website="https://christosmarg.xyz"
author="Christos Margiolis"
blogdir="blog"
draftdir=".drafts"
blogindex="blogindex.html"
index="index.html"
rssfile="rss.xml"
template="template.html"
[ -z "$EDITOR" ] && EDITOR="nano"

[ ! -d "$blogdir" ] &&
    read -erp "Blog directory doesn't exist. Initialize it here (y/n)? " initblogdir &&
    [ "$initblogdir" = "y" ] && mkdir -pv $blogdir

listposts()
{
    printf "Listing posts in %s (Total: %d)\n" "$1" "$(ls $1 -I "*final*" | wc -l)"
    ls -rc $1 -I "*-final*" | awk -F '/' '{print $NF}' | nl
    read -erp "Choose a post to by number: " num && [ -z "$num" ] && echo "No post selected." && exit
    blogpost=$(ls -rc $1 -I "*-final*" | nl | grep -w " $num" | awk '{print $2}' | sed "s/\..*//")
}

newpost()
{
    mkdir -p $draftdir
    read -erp "Title: " title && [ -z "$title" ] && echo "Please specify a title." && exit
    blogpost=$(echo $title | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
    [ -f "$blogdir/$blogpost.html" ] && echo "File exists already." && exit
    $EDITOR "$draftdir/$blogpost.html"
    sed "s/TITLE/$title/g;s/HEADER/$title/g;s/AUTHOR/$author/g;" $template > $draftdir/$blogpost-final.html
}

publish()
{
    title=$(grep "<title>" $draftdir/$blogpost-final.html | sed "s/<title>//;s/<\/title>//;s/ *//;")
    sed -i "/<\!--BLOG-->/r $draftdir/$blogpost.html" $draftdir/$blogpost-final.html
    sed "s/</\&lt;/g;s/>/\&gt;/g;" "$draftdir/$blogpost.html" > $draftdir/$blogpost.xml
    cp $draftdir/$blogpost-final.html $blogdir && mv $blogdir/$blogpost-final.html $blogdir/$blogpost.html
    printf "\t\t\t\t<li>%s &ndash; <a href=\"%s\">%s</a></li>\n" "$(date '+%Y %b %d')" "$blogdir/$blogpost.html" "$title" | expand -t4 > $draftdir/$blogpost-htmlentry
    printf "<item>\n\t<title>%s</title>\n\t<guid>%s</guid>\n\t<pubDate>%s</pubDate>\n\t<description>\n\t\t%s\n\t</description>\n</item>\n" "$title" "$website/$blogdir/$blogpost.html" "$(date '+%a, %d %b %Y')" "$(cat $draftdir/$blogpost.xml)" | expand -t4 > $draftdir/$blogpost-rssentry

    sed -i "/<\!--BLOG $(date '+%B %Y')-->/r $draftdir/$blogpost-htmlentry" $blogindex && echo "Blogindex... done."
    sed -i "/<\!--BLOG-->/r $draftdir/$blogpost-htmlentry" $index && echo "Index... done"
    sed -i "/<\!--BLOG-->/r $draftdir/$blogpost-rssentry" $rssfile && echo "RSS... done"
    remove_last_index_entry && echo "Removing last entry from index file... done"
    remove_contents $draftdir && echo "Cleaning up .drafts... done"
    echo "Published $blogpost."
}

delete()
{
    [ $(($(echo "$blogpost" | wc -l))) -gt 1 ] && echo "Invalid choice" && exit
    [ "$1" = "$blogdir" ] &&
        sed -i "/$blogpost/d" $index $blogindex &&
        sed -ni "/<item>/{ :loop; N; s/<\\/item>/&/; T loop; s/$blogpost/&/; T keep; d }; :keep; p" $rssfile
    remove_contents $1 && echo "Removed $blogpost."
}

view()
{
    cat $draftdir/$blogpost-final.html > $draftdir/$blogpost-final-view.html
    title=$(grep "<title>" $draftdir/$blogpost-final-view.html | sed "s/<title>//;s/<\/title>//;s/ *//;")
    sed -i "/<\!--BLOG-->/r $draftdir/$blogpost.html" $draftdir/$blogpost-final-view.html
    $BROWSER $draftdir/$blogpost-final-view.html
}

remove_contents()
{
    ls $1 | grep -w $blogpost | sed "s/^/$1\//" | xargs rm
}

remove_last_index_entry()
{
    indexentries=$(sed "1,/<\!--BLOG-->/d" $index | grep "<li>") &&
        [ $(($(echo "$indexentries" | wc -l))) -gt 7 ] && 
        lastentry=$(echo "$indexentries" | tail -2 | head -1) &&
        sed -i "s|$lastentry||;" $index
}

case $1 in
    -n*) newpost ;;
    -p*) listposts $draftdir && publish ;;
    -e*) listposts $draftdir && $EDITOR $draftdir/$blogpost.html ;;
    -v*) listposts $draftdir && view ;;
    -t*) listposts $draftdir && delete $draftdir ;;
    -r*) listposts $blogdir  && $EDITOR $blogdir/$blogpost.html ;;
    -o*) listposts $blogdir  && $BROWSER $blogdir/$blogpost.html ;;
    -d*) listposts $blogdir  && delete $blogdir ;;
    -l*) listposts $blogdir ;;
    *)   printf "Usage: autoblog [OPTION]\n\nOptions:\n  -n\t\tNew post\n  -p\t\tPublish draft post\n  -e\t\tEdit draft post\n  -v\t\tView draft post in browser\n  -t\t\tDelete draft post\n  -r\t\tRevise published post\n  -o\t\tView published post in browser\n  -d\t\tDelete published post\n  -l\t\tList all published posts\n" ;;
esac
