.Dd sbrs\-VERSION
.Dt SBRS 1
.Os
.Sh NAME
.Nm sbrs
.Nd simple blog and RSS system
.Sh SYNOPSIS
.Nm
.Op Fl n Ar new post
.Op Fl p Ar publish draft
.Op Fl e Ar edit draft
.Op Fl v Ar view draft
.Op Fl t Ar delete draft
.Op Fl r Ar revise published
.Op Fl c Ar change title
.Op Fl o Ar view published
.Op Fl d Ar delete published
.Op Fl l Ar list all published
.Sh DESCRIPTION
.Nm
generates a blog post page and RSS feed.
.Sh OPTIONS
The options are as follows:
.Bl -tag -width Ds
.It Fl n Ar new post
Prompt the user to write a new blog post in HTML
.It Fl p Ar publish draft
Publish one of the posts stored in the .drafts directory. 
.It Fl e Ar edit draft
Edit one of the posts stored in the .drafts directory.
.It Fl v Ar view draft
View one of the posts stored in the .drafts directory.
.It Fl t Ar delete draft
Delete one of the posts stored in the .drafts directory.
.It Fl r Ar revise published
Revise a published post stored in the blog directory.
.It Fl c Ar change title
Change a published post's title.
.It Fl o Ar view published
View a published post stored in the blog directory on your default browser.
.It Fl d Ar delete published
Delete a published post stored in the blog directory.
.It Fl l Ar list all published
List all posts stored in the blog directory.
.El
.Pp
Only one option at a time can be used.
.Sh USAGE
.Pp
Run the script inside your website's main directory and edit the website and author
to match your own information. Make sure that the rest of the variables are properly
set to match your website's structure. By default, all blog posts are stored in blog/.
.Sh REQUIREMENTS
.Pp
The following files have to exist in the same directory
.Nm
is called:
.Bl -tag -width Ds
.It index.html
Main page.
.It blogindex.html
Blog page index.
.It template.html
A template file that will be used to format the blog post.
The TITLE, HEADER and AUTHOR fields must exist and be left as is.
.It rss.xml
The RSS feed.
.El
.Pp
.Nm
will search for <!--BLOG--> inside index.html and rss.xml
in order to put the blog post listings and RSS feed respectively. Inside blogindex.html
however, it will search for <!--BLOG [Month Year]--> (e.g <!--BLOG January 1800->).
.Sh AUTHORS
.An Christos Margiolis Aq Mt christos@christosmarg.xyz
