.Dd sbrs\-VERSION
.Dt SBRS 1
.Os
.Sh NAME
.Nm sbrs
.Nd simple blog and RSS system
.Sh SYNOPSIS
.Nm
.Bro
.Fl n |
.Fl p |
.Fl e |
.Fl v |
.Fl t |
.Fl r |
.Fl c |
.Fl o |
.Fl d |
.Fl l
.Sh DESCRIPTION
.Nm
generates a blog post page and RSS feed.
.Sh OPTIONS
The options are as follows:
.Bl -tag -width Ds
.It Fl n
Prompt the user to write a new blog post in HTML.
.Nm
will open the editor set in the 'EDITOR' environmental variable. In case
it is not set, it will set 'EDITOR'
.Xr Vim 1
.It Fl p
Publish one of the posts stored in the '.drafts' directory. After a post
has been published, it will be deleted from '.drafts' along with all the
files related to it and will be moved to 'blog'. This option also automatically
creates an RSS feed for the post.
.It Fl e
Edit one of the posts stored in the '.drafts' directory.
.It Fl v
View one of the posts stored in the '.drafts' directory.
.Nm
creates a temporary file that looks like the finished post, but is deleted
after
.Nm
has exited. The 'BROWSER' environmental variable has to be set
in order for this option to work.
.It Fl t
Delete one of the posts stored in the '.drafts' directory.
.It Fl r
Revise a published post stored in the 'blog' directory. After you're done
revising you don't need to re-publish the post again, since
.Nm
edits the post directly.
.It Fl c
Change a published post's title. This option will replace every instance
of the old title with the new one both. The filename will also
be changed.
.It Fl o
View a published post stored in the 'blog' directory on your default browser.
Same with the -v option; the 'BROWSER' environmental variable has to be set
in order for this option to work.
.It Fl d
Delete a published post stored in the 'blog' directory. This option will delete
the post from the blog's index file, the RSS feed, as well as the main page in
case it is found there too.
.It Fl l
List all posts stored in the 'blog' directory.
.El
.Pp
Only one option at a time can be used.
.Sh PREPARATION
.Pp
Inside the
.Nm
script, change the 'WEBSITE' and 'AUTHOR' variables to match your website's URL
and your name.
.Pp
In case you don't edit the script further, the structure of your website's
directory should look like this. The files below need to exist with the same
names.
.Pp
        ├── blog
        |   └── here reside your blog posts
        ├── index.html
        ├── blog.html
        ├── template.html
        └── rss.xml
.Pp
Inside 'index.html', 'blog.html' and 'rss.xml'
.Nm
will search for
<!--SBRS--> in order to put the blog post listings and RSS feed below it.
.Pp
The 'template.html' file is how you want your blog post's page to look like.
See my own 'template.html' for more. The 'TITLE', 'HEADER' and 'AUTHOR'
fields must exist and be left as is.
.Sh USAGE
.Pp
You must always run the script inside your website's main directory.
Run it with one of the following options. Only one option can be used
at a time.
.Sh NOTES
Do NOT edit the various comments that the script writes inside the files,
otherwise it'll not work properly, or work at all.
.Sh AUTHORS
.An Christos Margiolis Aq Mt christos@christosmarg.xyz
